#ifndef DATACPPLIB_H
#define DATACPPLIB_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include <QList>
#include <QVariant>
#include "eloginresponse.h"
#include "efirstsvcarg.h"
#include "tpreference.h"
#include "ebasesetup.h"
#include "emetaresponse.h"


class DATACPPLIB{
public:
	static QList<QMetaObject> getMeta() {
		return QList<QMetaObject>() 
			<<ELoginResponse::getMeta()
			<<EFirstSVCArg::getMeta()
			<<TPreference::getMeta()
			<<EMetaResponse::getMeta();
	}
};
#endif
