#ifndef DATABASE_H
#define DATABASE_H
/**
*@author Tezine Technologies
*Machine generated. DO NOT EDIT THIS FILE!
**/
#include <QList>
#include <QVariant>
#include "eloginresponse.h"
#include "efirstsvcarg.h"
#include "tpreference.h"


class DATABASE{
public:
	static QList<QMetaObject> getMeta() {
		return QList<QMetaObject>() 
			<<ELoginResponse::getMeta()
			<<EFirstSVCArg::getMeta()
			<<TPreference::getMeta();
	}
};
#endif
